project:
  type: website
  output-dir: docs
website:
  title: "LeaLambdin.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: fun.qmd
        text: Fun
      - href: resume.qmd
        text: Resume


